[project]
name = "nyc-311-requests"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
 "apache-airflow-providers-apache-kafka>=1.9.0",
 "apache-airflow-providers-postgres>=6.2.0",
]
